---
title: jessagillespie
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: jessagillespie@gmail.com
description: ";)"
baseurl: 
url: 
github_username: merehuman
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
source: src
destination: dist
sass:
  sass_dir: assets/_sass
js:
  js_dir: assets/_js
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
